/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdresseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdressenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Gibt eine Elektro-Aktion zurück.
     * 
     * @param guid GUID einer Elektro-Aktion.
     */
    apiV1AdressenGuidGet(guid: string, extraHttpRequestParams?: any): Observable<AdresseDTO>;

    /**
     * Erstellt oder speichert eine Adresse.
     * 
     * @param adresseDTO Das Adresse DTO Objekt, welches die Daten der zu erstellenden/speichernden Adresse enthält.
     */
    apiV1AdressenPost(adresseDTO?: AdresseDTO, extraHttpRequestParams?: any): Observable<AdresseDTO>;

}
