/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuftragsDefDTO } from '../model/models';
import { DokumentChoiceDTO } from '../model/models';
import { DokumentDefDTO } from '../model/models';
import { DokumentKatDTO } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefinitionenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Projekt-Definitionen abrufen.
     * 
     * @param guids 
     */
    apiV1DefinitionenDocCatsGet(guids?: Array<string>, extraHttpRequestParams?: any): Observable<Array<DokumentKatDTO>>;

    /**
     * 
     * 
     * @param sparten 
     * @param page 
     * @param limit 
     */
    apiV1DefinitionenDocCatsListGet(sparten?: Array<string>, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<Array<DokumentKatDTO>>;

    /**
     * 
     * 
     * @param auftragDef 
     * @param empfaenger 
     */
    apiV1DefinitionenDocChoicesGet(auftragDef?: string, empfaenger?: Array<string>, extraHttpRequestParams?: any): Observable<DokumentChoiceDTO>;

    /**
     * 
     * 
     */
    apiV1DefinitionenDocDefsGet(extraHttpRequestParams?: any): Observable<Array<DokumentDefDTO>>;

    /**
     * 
     * 
     * @param guid 
     */
    apiV1DefinitionenOrderDefsGetGuidGet(guid: string, extraHttpRequestParams?: any): Observable<AuftragsDefDTO>;

    /**
     * 
     * 
     * @param sparten 
     * @param page 
     * @param limit 
     */
    apiV1DefinitionenOrderDefsListGet(sparten?: Array<string>, page?: number, limit?: number, extraHttpRequestParams?: any): Observable<Array<AuftragsDefDTO>>;

}
