/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DsoDefDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DsoServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * cref.
     * 
     * @param guid GUID der Dso-Definition.
     */
    apiV1DsoDefsGuidGet(guid: string, extraHttpRequestParams?: any): Observable<DsoDefDTO>;

    /**
     * 
     * 
     * @param guid 
     */
    apiV1DsoGuidGet(guid: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @param guid 
     * @param file Der Datenstrom des/der hoch zu ladenden Dokumentobjektes/-Datei.
     * @param dsoDef Die Dso-Defintions GUID des hoch geladenen Dokumentes.
     * @param overwrite Bestehendes File - Objekt / Datei überschreiben.
     */
    apiV1DsoGuidPost(guid: string, file: Blob, dsoDef?: string, overwrite?: boolean, extraHttpRequestParams?: any): Observable<{}>;

}
