/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EAktionDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EAktionenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Gibt eine Elektro-Aktion zurück.
     * 
     * @param guid GUID einer Elektro-Aktion.
     */
    apiV1EAktionenGuidGet(guid: string, extraHttpRequestParams?: any): Observable<EAktionDTO>;

    /**
     * Erstellt oder speichert eine Aktion in der Elektro Sparte.
     * 
     * @param eAktionDTO Das Elektro-Aktion DTO Objekt, welches die Daten der zu erstellenden/speichernden Aktion enthält.
     */
    apiV1EAktionenPost(eAktionDTO?: EAktionDTO, extraHttpRequestParams?: any): Observable<EAktionDTO>;

}
