/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EAnlageDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EAnlagenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Gibt Elektro-Anlagen pro Gebäude zurück.
     * 
     * @param guid Gebäude-GUID.
     */
    apiV1EAnlagenByGebaeudeIdGuidGet(guid: string, extraHttpRequestParams?: any): Observable<EAnlageDTO>;

    /**
     * Gibt eine Elektro-Anlage zurück.
     * 
     * @param guid Primärer Schlüssel einer Elektro-Anlage.
     */
    apiV1EAnlagenGuidGet(guid: string, extraHttpRequestParams?: any): Observable<EAnlageDTO>;

    /**
     * Erstellt oder speichert eine Anlage in der Elektro Sparte.
     * 
     * @param eAnlageDTO Das Elektro-Anlage DTO Objekt, welches die Daten der zu erstellenden/speichernden Anlage enthält.
     */
    apiV1EAnlagenPost(eAnlageDTO?: EAnlageDTO, extraHttpRequestParams?: any): Observable<EAnlageDTO>;

}
