/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EDokumentTypDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EDokumenteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param guid 
     */
    apiV1EDokumenteGuidObjectGet(guid: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @param guid 
     * @param dokument Der Datenstrom des/der hoch zu ladenden Dokumentobjektes/-Datei.
     * @param dokumentTyp Die Dokumenttyp-GUID des hoch geladenen Dokumentes.
     * @param overwrite Bestehendes Dokument - Objekt / Datei überschreiben.
     */
    apiV1EDokumenteGuidObjectPost(guid: string, dokument: Blob, dokumentTyp?: string, overwrite?: boolean, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Ruf den Dokumenttyp der Elektro Sparte mit anhand dessen GUID ab.
     * 
     * @param guid GUID des Dokumenttyps.
     */
    apiV1EDokumenteTypesGuidGet(guid: string, extraHttpRequestParams?: any): Observable<EDokumentTypDTO>;

}
