/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ELeistungDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ELeistungenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Gibt eine Elektro-Leistung zurück.
     * 
     * @param guid GUID einer Elektro-Leistung.
     */
    apiV1ELeistungenGuidGet(guid: string, extraHttpRequestParams?: any): Observable<ELeistungDTO>;

    /**
     * Erstellt oder speichert eine Leistung in der Elektro Sparte.
     * 
     * @param eLeistungDTO Das Elektro-Leistung DTO Objekt, welches die Daten der zu erstellenden/speichernden Leistung enthält.
     */
    apiV1ELeistungenPost(eLeistungDTO?: ELeistungDTO, extraHttpRequestParams?: any): Observable<ELeistungDTO>;

}
