/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EProjektDTO } from '../model/models';
import { EProjektViewDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EProjekteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param onlyActive 
     */
    apiV1EProjekteCountGet(onlyActive?: boolean, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Gibt ein Elektro-Projekt anhand der GUID des Elektro-Auftrags zurück.
     * 
     * @param guid Die GUID des Elektro-Auftrag wessen Projekt abgerufen werden soll.
     */
    apiV1EProjekteGuidGet(guid: string, extraHttpRequestParams?: any): Observable<EProjektDTO>;

    /**
     * Gibt eine Liste mit Projekten zurück
     * 
     * @param limit Anzahl Records die zurückgegeben werden sollen
     * @param skip Anzahl von ausgelassenen Ergebnissen für Paging. z.B. 0 für erste Seite, 10 für zweite Seite.
     */
    apiV1EProjekteListGet(limit?: number, skip?: number, extraHttpRequestParams?: any): Observable<Array<EProjektViewDTO>>;

    /**
     * Erstellt ein neues Projekt in der Elektro Sparte.
     * 
     * @param eProjektDTO Das Elektro-Projekt DTO Objekt, welches die Daten des zu erstellenden Projektes enthält.
     */
    apiV1EProjektePost(eProjektDTO?: EProjektDTO, extraHttpRequestParams?: any): Observable<EProjektDTO>;

    /**
     * Sucht nach Projekten in den verschiedenen Tabellen und Feldern (Gebäude, Auftrag, Empfänger) mittels Suchbegriff.
     * 
     * @param text Suchbegriff, nach welchem gesucht werden soll. Der Text soll nicht leer sein.
     * @param mandant Mandant des Projekts. Falls der Mandant leer wird über alle Projekte gesucht.
     * @param limit Anzahl an Projekten die zurückgeliefert werden sollen. Wert zwischen 1 und 100. Default ist 10.
     * @param skip Anzahl von ausgelassenen Ergebnissen für Paging. z.B. 0 für erste Seite, 10 für zweite Seite.
     */
    apiV1EProjekteSuchenGet(text?: string, mandant?: string, limit?: number, skip?: number, extraHttpRequestParams?: any): Observable<Array<EProjektViewDTO>>;

}
