/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GebaeudeDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GebaeudeServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Speichern einer Liste von Geräten
     * 
     * @param gebaeudeDTO 
     */
    apiV1GebaeudeGeraetePut(gebaeudeDTO?: GebaeudeDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Gibt ein Gebäude zurück.
     * 
     * @param guid GUID eines Gebäudes.
     */
    apiV1GebaeudeGuidGet(guid: string, extraHttpRequestParams?: any): Observable<GebaeudeDTO>;

    /**
     * Insert eines Gebäudes
     * 
     * @param gebaeudeDTO 
     */
    apiV1GebaeudePost(gebaeudeDTO?: GebaeudeDTO, extraHttpRequestParams?: any): Observable<GebaeudeDTO>;

    /**
     * Update eines Gebäudes
     * 
     * @param gebaeudeDTO 
     */
    apiV1GebaeudePut(gebaeudeDTO?: GebaeudeDTO, extraHttpRequestParams?: any): Observable<GebaeudeDTO>;

}
