/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeschStelleDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GeschStellenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Gibt alle GeschStellen einer Holding zurück.
     * 
     * @param holdingGuId Primärer Schlüssel (Guid) einer Holding.
     */
    apiV1GeschStellenAllHoldingGuIdGet(holdingGuId: string, extraHttpRequestParams?: any): Observable<Array<GeschStelleDTO>>;

    /**
     * Gibt eine GeschStelle zurück.
     * 
     * @param guid Primärer Schlüssel (Guid)  einer GeschStelle.
     */
    apiV1GeschStellenGuidGet(guid: string, extraHttpRequestParams?: any): Observable<GeschStelleDTO>;

    /**
     * Löscht eine GeschStelle
     * Die GeschStelle wird nur dann gelöscht, wenn sie keine weiteren Abhängigkeiten hat.
     * @param id Primärer Schlüssel der GeschStelle
     */
    apiV1GeschStellenIdDelete(id: number, extraHttpRequestParams?: any): Observable<GeschStelleDTO>;

    /**
     * Insert einer GeschStelle
     * 
     * @param geschStelleDTO 
     */
    apiV1GeschStellenPost(geschStelleDTO?: GeschStelleDTO, extraHttpRequestParams?: any): Observable<GeschStelleDTO>;

    /**
     * Update einer GeschStelle
     * 
     * @param geschStelleDTO GeschStelleDTO
     */
    apiV1GeschStellenPut(geschStelleDTO?: GeschStelleDTO, extraHttpRequestParams?: any): Observable<GeschStelleDTO>;

    /**
     * Sucht nach Geschäftsstellen in den verschiedenen Feldern (Firma, Adresse, Bemerkungen, Email usw.) mittels Suchbegriff.
     * 
     * @param text Suchbegriff, nach welchem gesucht werden soll. Der Text soll nicht leer sein.
     * @param mandant Mandant der Geschäftsstellen. Falls der Mandant leer wird über alle Geschäftsstellen gesucht.
     * @param limit Anzahl an Geschäftsstellen die zurückgeliefert werden sollen. Wert zwischen 1 und 100. Default ist 10.
     * @param skip Anzahl von ausgelassenen Ergebnissen für Paging. z.B. 0 für erste Seite, 10 für zweite Seite.
     */
    apiV1GeschStellenSuchenGet(text?: string, mandant?: string, limit?: number, skip?: number, extraHttpRequestParams?: any): Observable<Array<GeschStelleDTO>>;

}
