/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PostleitzahlenDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PostleitzahlenServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Gibt Gemeinden und Orte pro PLZ zurück.
     * 
     * @param plz 
     */
    apiV1PostleitzahlenPlzGet(plz: string, extraHttpRequestParams?: any): Observable<Array<PostleitzahlenDTO>>;

}
