/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeistungsDefDTO } from './leistungsDefDTO';
import { MultiLangText } from './multiLangText';


/**
 * Diese Klasse repräsentiert ein Datentransferobjekt für Auftragsdefinitionen.
 */
export interface AuftragsDefDTO { 
    /**
     * Die eindeutige GUID dieser Auftragsdefinition.
     */
    guid: string;
    /**
     * Die Sparte des Auftrags, welcher durch diese Definition definiert wird.
     */
    sparte?: string | null;
    /**
     * Die Sequenz-Nummer für die Sortierreihenfolge.
     */
    sequenzNr?: number;
    /**
     * Ein Indikator der Anzeigt, ob diese Auftragsdefinition aktuell aktiviert ist oder nicht.
     */
    aktiv?: boolean;
    bezeichnung?: MultiLangText;
    /**
     * Die in diesem Auftrag enthaltenen Leistungen bzw. die entsprechenden Leistungsdefinitionen.
     */
    leistungsDefs?: Array<LeistungsDefDTO> | null;
}

