/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignaturDTO } from './signaturDTO';
import { DokumentTransferKanal } from './dokumentTransferKanal';
import { DokumentTransferHistoryDTO } from './dokumentTransferHistoryDTO';
import { DokumentDefDTOApp } from './dokumentDefDTOApp';
import { DokumentStatus } from './dokumentStatus';
import { DsoDTO } from './dsoDTO';


/**
 * Diese Klasse repräsentiert ein Datentransferobjekt für Elektro-Formular Entitäten.
 */
export interface DokumentDTO { 
    /**
     * Die <see cref=\"P:BrunnerInformatik.NextGen.App.ViewModel.DokumentDTO.Guid\">GUID</see> des Mandanten, in welchem sich dieses Formular befindet.
     */
    mandant: string;
    /**
     * Die <see cref=\"P:BrunnerInformatik.NextGen.App.ViewModel.DokumentDTO.Guid\">GUID</see> dieses Formulars.
     */
    guid?: string | null;
    dso?: DsoDTO;
    antwort?: DokumentDTO;
    dokumentDef?: DokumentDefDTOApp;
    /**
     * Die <see cref=\"P:BrunnerInformatik.NextGen.App.ViewModel.DokumentDTO.Guid\">GUID</see> des Empfängers dieses Formulars.
     */
    empfaenger?: string | null;
    fortschritt?: number;
    status?: DokumentStatus;
    antwortKanal?: DokumentTransferKanal;
    antwortEMail?: string | null;
    antwortM20?: string | null;
    beilagen?: Array<DokumentDTO> | null;
    signaturen?: Array<SignaturDTO> | null;
    transferHistory?: Array<DokumentTransferHistoryDTO> | null;
}

