/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DokumentTransferKanal } from './dokumentTransferKanal';
import { TransferTyp } from './transferTyp';


/**
 * Diese Klasse repräsentiert ein Data-Transfer-Object für Elektro-Formular Entitäten.
 */
export interface DokumentTransferHistoryDTO { 
    /**
     * Die <see cref=\"T:System.Guid\">GUID</see> des Mandanten, in welchem sich das betroffene Formular befindet.
     */
    mandant: string;
    /**
     * Die <see cref=\"T:System.Guid\">GUID</see> des Dokuments.
     */
    dokument: string;
    typ?: TransferTyp;
    kanal?: DokumentTransferKanal;
    /**
     * Die <see cref=\"T:System.Guid\">GUID</see> des Absenders.
     */
    absender?: string;
    /**
     * Die <see cref=\"T:System.Guid\">GUID</see> des Empfängers.
     */
    empfaenger?: string | null;
    /**
     * Der Zeitstempel <see cref=\"T:System.DateTime\">GUID</see> des History-Eintrags.
     */
    timestamp?: string;
    /**
     * Die Grösse des Dokuments zum Zeitpunkt der Erstelleung des History-Eintrags (wird serverseitig berechnet).
     */
    size?: number | null;
    /**
     * Der Hashwert <see cref=\"T:System.DateTime\">GUID</see> des Dokuments zum Zeitpunkt der Erstelleung des History-Eintrags (SHA256 wird serverseitig berechnet).
     */
    hash?: string | null;
}

