/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Diese Klasse repräsentiert ein Datentransferobjekt für eine Dokumentdefinition.
 */
export interface DokumentDefDTOApp { 
    /**
     * Die eindeutige <see cref=\"T:System.Guid\">GUID</see> dieser Dokumentdefinition.
     */
    guid?: string | null;
    /**
     * Die optionale <see cref=\"T:System.Guid\">GUID</see> des Basisdokumenttyps welcher durch diesen spezialisiert wird.
     */
    baseGUID?: string | null;
    /**
     * Die ID des Formularsets zu dem diese Dokumentdefinition gehört.
     */
    formSetID?: number;
    /**
     * Die Dokumentkategorie zu welchem diese Dokumentdefinition gehört.
     */
    category?: string;
    /**
     * Eindeutiger Name dieser Dokumentdefinition. Verbindung zwischen DataDic und Schema.
     */
    name?: string | null;
    /**
     * Der Kurzname/Anzeigename dieser Dokumentdefinition.
     */
    shortName?: string | null;
    /**
     * Der lange bzw. vollständige Name dieser Dokumentdefinition.
     */
    longName?: string | null;
    /**
     * Der Name des Herausgebers dieses Formulars.
     */
    issuer?: string | null;
    /**
     * Der optionale vollständige Name dieser Dokumentdefinition wie er vom Herausgeber spezifiziert wurde.
     */
    nameByIssuer?: string | null;
    /**
     * Eine optionale Beschreibung für diese Dokumentdefinition.
     */
    description?: string | null;
    /**
     * Der IETF BCP 47 Sprachcode im Format: \'de-CH\', welcher die Sprache des durch diese Dokumentdefinition  definierten Dokumentes angibt.
     */
    languageCode?: string | null;
    /**
     * Dies Version dieser Dokumentdefinition.
     */
    version?: number;
}

