/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpfaengerDTO } from './empfaengerDTO';
import { AuftragsDefDTO } from './auftragsDefDTO';
import { DokumentDefDTO } from './dokumentDefDTO';


/**
 * Diese Klasse repräsentiert ein Datentransferobjekt für Dokument Choices.
 */
export interface DokumentChoiceDTO { 
    projektDef?: AuftragsDefDTO;
    /**
     * Eine Dictionary-Instanz, welche die GUID der Empfänger und die entsprechenden `EmpfaengerDTO` Instanzen  beinhaltet.
     */
    empfaenger?: { [key: string]: EmpfaengerDTO; } | null;
    /**
     * Eine Dictionary-Instanz, welche die GUID der Empfänger und eine Liste der konkreten Dokumentdefinitionen der zu  erstellenden Dokumenten enthält.
     */
    dokumentDefs?: { [key: string]: Array<DokumentDefDTO>; } | null;
}

