/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DokumentDTO } from './dokumentDTO';
import { AdresseDTO } from './adresseDTO';
import { EAuftragPhaseDTO } from './eAuftragPhaseDTO';


/**
 * Diese Klasse repräsentiert ein Data-Transfer-Object für Elektro-Aufträge Entitäten.
 */
export interface EAuftragDTO { 
    /**
     * Primärschlüssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID des Elektro-Auftrag.
     */
    guid?: string | null;
    /**
     * 0, leer = Nichts, 1 = exportiert, (2 = re-importiert).
     */
    exportStatus?: number | null;
    /**
     * GUID für Dossier-Export und -Synchronisation.
     */
    exportGUID?: string | null;
    /**
     * Auftragsnummer vergeben vom Anwender.
     */
    auftragsNr: string;
    /**
     * Internes Stichwort für Ausdruck auf Formularen.
     */
    stichwort?: string | null;
    /**
     * Auftragskategorie.
     */
    kategorie?: string | null;
    /**
     * Anwender-Sprache.
     */
    sprache?: string | null;
    /**
     * Kostenstelle 1.
     */
    habenKst1?: string | null;
    /**
     * Kostenstelle 2.
     */
    habenKst2?: string | null;
    /**
     * Netzbetreiberin, Fremdschlüssel auf GeschPartner.
     */
    idWerk?: number | null;
    /**
     * VnbGUID aus EVU-Pack-Datei, wird gesetzt wenn Daten vom VNB abgerufen werden oder ein Formular an ein VNB mit  GUID gesendet wird.
     */
    vnbGUID?: string | null;
    /**
     * Evu-Adress-Plugin-Name von stromlieferndem VNB.
     */
    stromlieferVnb?: string | null;
    /**
     * Werk-Nr. für die Formulare.
     */
    werkNr?: string | null;
    /**
     * Jahr der Werk-Nr. für die Formulare.
     */
    jahr?: number | null;
    /**
     * Datum der Inbetriebnahme.
     */
    datumInbetrieb?: string | null;
    /**
     * Notizen (im Dossier direkt bearbeitbar).
     */
    beschrieb?: string | null;
    /**
     * Auftragsbeschrieb (wird auf Formulare übernommen).
     */
    bemerkungen?: string | null;
    /**
     * Referenz-Nummer für externen Datenabgleich/Datenübernahme/Datenaustausch.
     */
    referenzNr?: string | null;
    /**
     * CRC32 des importierten Dossiers.
     */
    importCRC?: number | null;
    /**
     * Extern befüllte Felder, welche nun im Programm gesperrt sind.
     */
    gesperrteFelder?: string | null;
    /**
     * GUID der Auftragsdefinition, welche auch die Auftrags-Art, z.B. Bauprojekt, PK, Temporäre Installation, usw...  bestimmt.
     */
    guiD_AuftragDef?: string | null;
    /**
     * Ersteller des Auftrags, 1 = Installateur, 2 = Kontrolleur, 4 = EVU.
     */
    ersteller?: number | null;
    /**
     * true = Dieser Elektro-Auftrag ist erledigt/abgeschlossen.
     */
    erledigt?: boolean;
    /**
     * Guid des Auftraggebers.
     */
    guidAuftraggeber?: string | null;
    adresseAuftraggeber?: AdresseDTO;
    /**
     * Auftraggeber ist Gebäude-Eigentümer.
     */
    auftraggeberIstGebEigentuemer?: boolean | null;
    /**
     * <br>               Projektdaten, wie sie aus einem externen System importiert oder über die API übermittelt wurden.                <note type=\"important\">               Dieses Feld muss `null` sein oder ein gültiges JSON Objekt!              </note>
     */
    externalData?: any | null;
    guidEmpfaengerVnb?: string | null;
    guidEmpfaengerGemeinde?: string | null;
    guidEmpfaengerPronovo?: string | null;
    /**
     * Die Phasen dieses Elektro-Auftrags.
     */
    phasen?: Array<EAuftragPhaseDTO> | null;
    /**
     * Alle Dokumente im Dokumentpool dieses Auftrages.
     */
    dokumente?: Array<DokumentDTO> | null;
}

