/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This enumeration defines all the states a document can be in.
 */
export type EfoDocumentStatus = 0 | 20 | 40 | 50 | 70 | 100 | 105 | 110 | 120;

export const EfoDocumentStatus = {
    None: 0 as EfoDocumentStatus,
    InProcess: 20 as EfoDocumentStatus,
    PartiallySigned: 40 as EfoDocumentStatus,
    Signed: 50 as EfoDocumentStatus,
    Sent: 70 as EfoDocumentStatus,
    Approved: 100 as EfoDocumentStatus,
    ApprovedWithMeasures: 105 as EfoDocumentStatus,
    Finished: 110 as EfoDocumentStatus,
    Rejected: 120 as EfoDocumentStatus
};

