/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EfoDocumentStatus } from './efoDocumentStatus';


/**
 * This data transfer object (DTO) represents a document of an ElektroForm electric project.
 */
export interface EfoDocumentDTO { 
    /**
     * The GUID of the tenant, in which this document is stored.
     */
    tenant: string;
    /**
     * The GUID of this document as soon as the document has been created, otherwise the `null` value.
     */
    guid?: string | null;
    /**
     * The category GUID of this document.
     */
    category?: string;
    /**
     * The GUID that uniquely identifies this document\'s type/definition as soon as the document has been created,  otherwise the `null` value.
     */
    definition?: string | null;
    /**
     * The sequence number in which order this document is to be shown.
     */
    index?: number;
    /**
     * The title of this document.
     */
    title?: string | null;
    status?: EfoDocumentStatus;
    /**
     * Gets the GUID of this document\'s recipient.
     */
    recipient?: string | null;
    /**
     * The attachments of this document.
     */
    attachments?: Array<EfoDocumentDTO> | null;
    /**
     * The document\'s Deep-Link except for attachements.
     */
    deepLink?: string | null;
}

