/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EfoEProjectState } from './efoEProjectState';
import { EfoEProjectInfoPhaseProgressDTO } from './efoEProjectInfoPhaseProgressDTO';


/**
 * This data transfer object (DTO) provides a summary of an ElektroForm electric project.
 */
export interface EfoEProjectInfoDTO { 
    /**
     * The tenant in which this ElektroForm electric project is stored.
     */
    tenant?: string;
    /**
     * The ElektroForm electric project GUID.
     */
    guid?: string;
    /**
     * The user specified order number of this project.
     */
    orderNumber?: string | null;
    /**
     * The user specified building number of this project.
     */
    buildingNumber?: string | null;
    /**
     * The keyword for this project.
     */
    keyword?: string | null;
    /**
     * The street name of this project\'s building.
     */
    street?: string | null;
    /**
     * The house number of this project\'s building.
     */
    houseNumber?: string | null;
    /**
     * The postal code of this project building\'s address.
     */
    postalCode?: string | null;
    /**
     * The city of the project building\'s address.
     */
    city?: string | null;
    /**
     * A collection of project phase progress objects, representing the progress of each individual project phase.
     */
    phaseProgress?: Array<EfoEProjectInfoPhaseProgressDTO> | null;
    /**
     * The total progress of this project as a normalized (0.0f...1.0f) percentage value.
     */
    projectProgress?: number;
    projectState?: EfoEProjectState;
}

