/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This data transfer object (DTO) represents a recipient of a document within an ElektroForm electric project.
 */
export interface EfoRecipientDTO { 
    /**
     * The GUID of this recipient.
     */
    guid: string;
    /**
     * The GUID of this recipient\'s category.
     */
    category?: string;
    /**
     * The display name of this recipient.
     */
    displayName?: string | null;
}

