/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EFormularAntwortKanal = 0 | 1 | 2 | 4 | 8 | 16 | 1024;

export const EFormularAntwortKanal = {
    Undefiniert: 0 as EFormularAntwortKanal,
    Papier: 1 as EFormularAntwortKanal,
    EMail: 2 as EFormularAntwortKanal,
    EF02: 4 as EFormularAntwortKanal,
    EF08: 8 as EFormularAntwortKanal,
    EF14: 16 as EFormularAntwortKanal,
    M20: 1024 as EFormularAntwortKanal
};

