/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EGeraetDTO { 
    guidMandant: string;
    guid?: string | null;
    guidGebaeude?: string;
    typ: string;
    /**
     * Der eindeutige Schlüssel der Komponente sofern diese aus einer Komponentendatenbank abgerufen wurde, ansonsten  der `null` Wert.                Dieser Schlüssel muss als ordinaler Text unter Berücksichtigung der Gross-/Kleinschreibung verglichen werden.
     */
    komponenteID?: string | null;
    bezeichnung?: string | null;
    hersteller: string;
    anzahl: number;
    daten?: string | null;
    creaDate?: string | null;
    modDate?: string | null;
}

