/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EAktionDTO } from './eAktionDTO';


/**
 * Diese Klasse repräsentiert ein Datentransferobjekt für Elektro-Leistungen Entitäten.
 */
export interface ELeistungDTO { 
    /**
     * Primärschlüssel: DB-Interne ID der Elektro-Leistung.
     */
    id?: number | null;
    /**
     * Primärschlüssel: GUID des Mandanten.
     */
    mandant: string;
    /**
     * GUID der Elektro-Leistung.
     */
    guid?: string | null;
    /**
     * Leistungsdefinition, Fremdschlüssel zu LeistungDef.
     */
    iD_LeistungDef?: number | null;
    /**
     * GUID der Leistungsdefinition.
     */
    guiD_LeistungDef?: string | null;
    /**
     * Die Phase des Auftrags, zu welcher diese Leistung gehört.
     */
    auftragsPhase?: string;
    /**
     * Die Elektro-Anlage auf welche sich diese Leistung bezieht.
     */
    anlage?: string;
    /**
     * Elektro-Leistungsnummer.
     */
    leistungsNr?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufügen (ELeistungen->Bezeichnung)!
     */
    bezeichnung?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufügen (ELeistungen->Kuerzel)!
     */
    kuerzel?: string | null;
    /**
     * Nähere Bezeichnung der Leistung.
     */
    zusatzText?: string | null;
    /**
     * TODO: Feldbeschreibung hinzufügen (ELeistungen->Datum)!
     */
    datum?: string | null;
    /**
     * Installateur-Firma, Fremdschlüssel zu GeschPartner.
     */
    iD_Installateur?: number | null;
    /**
     * Sachbearbeiter der Installateur-Firma.
     */
    instSachb?: string | null;
    /**
     * Kontrolleur-Firma, Fremdschlüssel zu GeschPartner.
     */
    iD_Kontrolleur?: number | null;
    /**
     * Sachbearbeiter der Kontrolleur-Firma.
     */
    kontrSachb?: string | null;
    /**
     * Sachbearbeiter Technisch, Fremdschlüssel zu Mitarbeiter.
     */
    iD_SachbTechn?: number | null;
    /**
     * Sachbearbeiter Administrativ, Fremdschlüssel zu Mitarbeite.
     */
    iD_SachbAdmin?: number | null;
    /**
     * Werk-Nr. für die Formulare.
     */
    werkNr?: string | null;
    /**
     * Jahr der Werk-Nr. für die Formulare.
     */
    jahr?: number | null;
    /**
     * Budgetierter Zeitaufwand.
     */
    budgetZeit?: number | null;
    /**
     * Budgetierter Geldbetrag.
     */
    budgetBetrag?: number | null;
    /**
     * true = Die Leistung ist erledigt/erbracht worden.
     */
    erledigt?: boolean | null;
    /**
     * Datum der Offerte.
     */
    offertDatum?: string | null;
    /**
     * Datum der Auftragserteilung.
     */
    auftragsDatum?: string | null;
    /**
     * Datum und Uhrzeit zu beginn der Kontrolle.
     */
    kontrollDatumVon?: string | null;
    /**
     * Datum und Uhrzeit am Ende der Kontrolle.
     */
    kontrollDatumBis?: string | null;
    /**
     * VSEK Statistikart, Fremdschlüssel zu VSEKStatistikArt.
     */
    iD_VSEKStatistikArt?: number | null;
    /**
     * true = Es wurden Mängel festgestellt.
     */
    maengel?: boolean | null;
    /**
     * Datum der Mängelbehebung.
     */
    behebungDatum?: string | null;
    /**
     * Datum der Rechnungsstellung.
     */
    rechnungDatum?: string | null;
    /**
     * Fixierter Briefempfänger, Fremdschlüssel zu Adressen.
     */
    iD_KorrespAdr?: number | null;
    /**
     * Den vom VNB als nächstes erwarteter Formular-Typ (Q = SiNa.
     */
    naechstFormTyp?: string | null;
    /**
     * Frist vom VNB des nächsten erwarteten Formulars.
     */
    naechstFormFrist?: string | null;
    /**
     * Geplantes Abschlussdatum dieser Elektro-Leistung.
     */
    geplantEndeDatum?: string | null;
    index?: number | null;
    aktionen?: Array<EAktionDTO> | null;
}

