/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmpfaengerDTO { 
    guid?: string;
    kategorien?: Array<string> | null;
    stichwort?: string | null;
    packName?: string | null;
    werkName?: string | null;
    designUrlName?: string | null;
    aktivVon?: string | null;
    aktiv?: boolean;
    iaNrInst?: boolean | null;
    firma1?: string | null;
    firma2?: string | null;
    adresse?: string | null;
    adrzusatz?: string | null;
    plz?: string | null;
    ort?: string | null;
    telefonG?: string | null;
    email?: string | null;
    kanton?: string | null;
    gemeinde?: string | null;
    kategorieGuid?: string;
    modDate?: string | null;
}

