/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This data transfer object (DTO) represents a phase of an ElektroForm Electric-Project.
 */
export interface EProjectPhaseDTO { 
    /**
     * The GUID that uniquely identifies this project phase
     */
    guid?: string;
    /**
     * The order number in which a project\'s phases are to be shown.
     */
    index?: number;
}

