/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormularKategorieDTO { 
    guid?: string;
    shortName?: string | null;
    longName?: string | null;
    beilagen?: Array<FormularKategorieDTO> | null;
    legacyTyp?: string;
}

