/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HoldingDTO { 
    id?: number | null;
    mandant?: string | null;
    guid?: string | null;
    name?: string | null;
    aktiv?: boolean;
    creaDate?: string | null;
    creaUser?: string | null;
    modDate?: string | null;
    modUser?: string | null;
}

