/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityDescriptor } from './identityDescriptor';


export interface IdentityContext { 
    tenant?: string;
    holding?: string;
    office?: string | null;
    employee?: string;
    impersonate?: IdentityDescriptor;
}

