/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AktionsDefinitionDTO } from './aktionsDefinitionDTO';
import { MultiLangText } from './multiLangText';


export interface LeistungsDefinitionDTO { 
    guid?: string;
    sparte?: string | null;
    sequenzNr?: number;
    aktiv?: boolean;
    auftragsdefinition?: string | null;
    bezeichnung?: MultiLangText;
    kuerzel?: MultiLangText;
    beschreibung?: MultiLangText;
    guidKomponente?: string;
    aktionen?: Array<AktionsDefinitionDTO> | null;
}

