/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NaechsterSchritt = 0 | 1 | 2;

export const NaechsterSchritt = {
    Undefiniert: 0 as NaechsterSchritt,
    TAG_anzeigen: 1 as NaechsterSchritt,
    PDF_SiNa_direkt_Versenden: 2 as NaechsterSchritt
};

