/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ObjektTyp = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const ObjektTyp = {
    Undefiniert: 0 as ObjektTyp,
    Projekt: 1 as ObjektTyp,
    Adresse: 2 as ObjektTyp,
    Anlage: 3 as ObjektTyp,
    Geraet: 4 as ObjektTyp,
    GeschStelle: 5 as ObjektTyp,
    Mitarbeiter: 6 as ObjektTyp
};

