/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityDTO } from './identityDTO';
import { ResourceDTO } from './resourceDTO';


export interface PermissionSetDTO { 
    identity?: IdentityDTO;
    permissions?: Array<string> | null;
    roles?: Array<string> | null;
    roleSets?: Array<string> | null;
    timestamp?: string;
    resource?: ResourceDTO;
}

