/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProduktLizenzDTO } from './produktLizenzDTO';


export interface ProduktLizenzGutscheinDTO { 
    holdingNotFound?: boolean;
    gutscheinNotFound?: boolean;
    gutscheinVerbraucht?: boolean;
    produktLizenz?: ProduktLizenzDTO;
}

