/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterEigentuemerDTO { 
    vorname?: string | null;
    nachname?: string | null;
    adresse?: string | null;
    adressZusatz?: string | null;
    postleitzahl?: string | null;
    ort?: string | null;
    eMail?: string | null;
    telefon?: string | null;
}

