/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransferTyp = 0 | 10 | 20 | 30 | 40;

export const TransferTyp = {
    Undefiniert: 0 as TransferTyp,
    Druck: 10 as TransferTyp,
    Versand: 20 as TransferTyp,
    EmpfangBestaetigt: 30 as TransferTyp,
    Empfang: 40 as TransferTyp
};

