/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransferKanal = 0 | 1 | 2 | 1024 | 1025;

export const TransferKanal = {
    Undefiniert: 0 as TransferKanal,
    Papier: 1 as TransferKanal,
    EMail: 2 as TransferKanal,
    M20: 1024 as TransferKanal,
    Pronovo: 1025 as TransferKanal
};

