/**
 * Next-Gen App API
 * Die REST Web-Schnittstelle zu der Next-Gen App Anwendung
 *
 * The version of the OpenAPI document: v1
 * Contact: info@brunnerinformatik.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SignatureRole = 0 | 1 | 10 | 15 | 20 | 25 | 100 | 110 | 120 | 130;

export const SignatureRole = {
    Undefiniert: 0 as SignatureRole,
    BasisAnwender: 1 as SignatureRole,
    FachkundigerElektroInstallateur: 10 as SignatureRole,
    BewilligungsElektroinhaberInstallateur: 15 as SignatureRole,
    FachkundigerElektroKontrolleur: 20 as SignatureRole,
    BewilligungsElektroinhaberKontrolleur: 25 as SignatureRole,
    BetriebseigenenInstallationen: 100 as SignatureRole,
    BesondereAnlagen: 110 as SignatureRole,
    Anschlussbewilligung: 120 as SignatureRole,
    FachkundigeInEigenheim: 130 as SignatureRole
};

